### ISSUE TITLE
Icon scaling issue on Fedora KDE Plasma 6

### ISSUE THREAD

**Issue by ams-sth** [Bali10050/Lightly#14]
At 125%, Icons suffer from scaling issue. I have noticed this issue persist in Boeh's Lightly version as well as on kvantum.

![Screenshot_20240920_184156](https://github.com/user-attachments/assets/d124a01b-1082-4384-b9de-036e6b6972b9)

**Comment by DeltaCopy** [comment]
Which Icon theme is that ?

**Comment by ams-sth** [comment]
Papirus Icon theme

**Comment by DeltaCopy** [comment]
On Wayland I see the same icon is indeed blurry when scaling is set to 125%
On X11 the icon is clear.

![image](https://github.com/user-attachments/assets/a2275406-cb28-4e9b-9834-5e34ab0a5075)

If there is no issue using the Breeze application style maybe some changes need to brought across to Lightly

**Comment by DeltaCopy** [comment]
Can you check if adding the following to `/etc/environment` fixes this issue ?

`QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor`

Restart to pick up the change.

**Comment by ams-sth** [comment]
After adding that line, the issue has been fixed. Thank you!

**Comment by DeltaCopy** [comment]
@Bali10050 FYI
https://github.com/Bali10050/Lightly/pull/17 created so that we track this inside the README.

**Comment by DeltaCopy** [comment]
thanks for merging @Bali10050 

@ams-sth please close this when you can.
