### ISSUE TITLE
Dependencies qt5-* not needed

### ISSUE THREAD

**Issue by Deinorius** [Bali10050/Lightly#16]
I was looking for some update on boehs, but because nothing changed, I looked for a fork and found yours. Thank you for continuing this work, Lightly just looks the best to me!
I would like to contribute, but my capabilities don't go beyond scripting.

About those qt5-* dependencies. Why are those listed? I built the last boehs version without any qt5 installed. Just did it right now from this repo and it installed without any issues.

Arch, Linux 6.10.10, Plasma 6.1.5

**Comment by Bali10050** [comment]
They are listed because I wanted to make it work on plasma 6 as fast as possible, and the method for that was to just list every dependency I could find. You can help me remove some that are unneeded

**Comment by DeltaCopy** [comment]
There are a couple of QT5 dependencies which are now considered legacy since we are now on Plasma 6.

See https://github.com/Bali10050/Lightly/pull/18

**Comment by ams-sth** [comment]
I removed these dependencies and was able to successfully build on Fedora 40.

"cmake(Qt5Core)" "cmake(Qt5Gui)" "cmake(Qt5DBus)" "cmake(Qt5X11Extras)" "cmake(Qt5UiTools)" "cmake(KF5GuiAddons)" "cmake(KF5WindowSystem)" "cmake(KF5I18n)" "cmake(KF5CoreAddons)" "cmake(KF5ConfigWidgets)" "cmake(KF5GlobalAccel)" "cmake(KF5IcoknThemes)" "cmake(KF5Init)" "cmake(KF5Crash)" "cmake(KF5KIO)" "cmake(KF5Notifications)" kf5-kpackage-devel kf5-kcmutils-devel kf5-frameworkintegration-devel

**Comment by DeltaCopy** [comment]
The current set of packages for Fedora 40 contains a lot of legacy packages originally meant for Plasma 5.
These packages are not required to build Lightly on Plasma 6.

On Fedora 40 I have tested the following and Lightly builds successfully with only the following packages installed.

1. git 
2. cmake 
3. extra-cmake-modules 
4. "cmake(KDecoration2)" 
5. kwin-devel
6. kf6-kcolorscheme-devel 
7. kf6-kguiaddons-devel
8.  kf6-ki18n-devel
9.  kf6-kiconthemes-devel
10. kf6-kirigami-devel
11. kf6-kcmutils-devel

See https://github.com/Bali10050/Lightly/pull/19

**Comment by Deinorius** [comment]
At least for Arch, you can reduce the list even further because the rest is being installed as dependencies. So there's just:

1. extra-cmake-modules
2. kdecoration
3. kcmutils
4. kcolorscheme
5. git

On the other side, every Plasma 6 user should have all three k* packages installed, as all are dependencies for kwin itself.
