### ISSUE TITLE
Adding bottom line as option

### ISSUE THREAD

**Issue by ams-sth** [Bali10050/Lightly#20]
A request to add a line pointed by red arrow.  IMO, it feels feels incomplete without it.

![Line Separator](https://github.com/user-attachments/assets/5051dcde-7611-4e19-84ec-8370a5d2dba2)

**Comment by ams-sth** [comment]
![Uploading Line Separator.png…]()

**Comment by Bali10050** [comment]
I have no idea how to do it, but I'll add it when I can

**Comment by ams-sth** [comment]
Sure. I will try from my side as well.

**Comment by tduck973564** [comment]
This line should span the whole footer. It just looks worse on the Accessibility KCM because they're not actual sub-pages like the other settings are.

**Comment by ams-sth** [comment]
@tduck973564 Do you mean like shown in image ? I actually want to make it look like shown in image.  Currently, I haven't been successful implementing in source code since I am no expert in cpp. The line shown in image occurs when I change application style and revert back to lightly but do not perform minimize and maximize activity  or reopen system settings.

![image](https://github.com/user-attachments/assets/d9609fc0-7b0c-488b-9c8a-2b8dc15758c4)

**Comment by tduck973564** [comment]
> @tduck973564 Do you mean like shown in image ? I actually want to make it look like shown in image. Currently, I haven't been successful implementing in source code since I am no expert in cpp. The line shown in image occurs when I change application style and revert back to lightly but do not perform minimize and maximize activity or reopen system settings.

Yes, that's what I mean. It just doesn't look as odd in the other sub-menus because, in those, the footer only spans the actual settings page.

**Comment by ams-sth** [comment]
Can you tell me which line of code should I alter to achieve that outcome ?

**Comment by tduck973564** [comment]
If I knew I wouldn't be commenting here 😁

**Comment by DeltaCopy** [comment]
> The line shown in image occurs when I change application style and revert back to lightly but do not perform minimize and maximize activity or reopen system settings.

I can repro this strange behavior too.
Breeze, Fusion, Kvantum renders the border line above the buttons just fine.

Further investigation is indeed required.

**Comment by christiantosta** [comment]
Personally I prefer to remove the other lines, like kvantum does. But how to do it? Perhaps setting it color to the same as window background? Brise (not Breeze, but the fork) have a patch to made this lines less visible.

**Comment by ams-sth** [comment]
@christiantosta Yeah removing other lines also work. It will make design look consistent.

**Comment by DeltaCopy** [comment]
@ams-sth see #38 which is merged into feature/qt-6 branch and see if this helps with rendering the bottom line inside systemsettings.
