### ISSUE TITLE
Fix progress bars(?)

### ISSUE THREAD

**Issue by tduck973564** [Bali10050/Lightly#22]
![image](https://github.com/user-attachments/assets/34bd2bc1-5e43-4769-818f-e4beff460322)

This is not how they're meant to look - are they inheriting from Fusion or something?
I don't know what element this is exactly.

**Comment by DeltaCopy** [comment]
I can't repro this using the default Breeze  theme.
Archlinux
Plasma 6.1.5
Qt Version: 6.7.2
Session: Wayland

![Screenshot_20240926_153912](https://github.com/user-attachments/assets/82c3992a-f107-4b77-8bee-910c2b9e573b)

Distro, Plasma version, QT version ?

**Comment by tduck973564** [comment]
Fedora Kinoite, Plasma 6.2 Beta (though I also see it on 6.1.5), Qt 6.7.2

**Comment by Bali10050** [comment]
It's probably someting fedora-related again.

![Screenshot_20240926_175747](https://github.com/user-attachments/assets/da020e62-3540-40be-b8be-cf044f34fdaf)

Try installing these as the dependencies, maybe something that was needed was deleted in the recent fedora cleanup:
```
sudo dnf install cmake extra-cmake-modules "cmake(Qt5Core)" "cmake(Qt5Gui)" "cmake(Qt5DBus)" "cmake(Qt5X11Extras)" "cmake(KF5GuiAddons)" "cmake(KF5WindowSystem)" "cmake(KF5I18n)" "cmake(KDecoration2)" "cmake(KF5CoreAddons)" "cmake(KF5ConfigWidgets)" "cmake(Qt5UiTools)" "cmake(KF5GlobalAccel)" "cmake(KF5IconThemes)" kwin-devel libepoxy-devel "cmake(KF5Init)" "cmake(KF5Crash)" "cmake(KF5KIO)" "cmake(KF5Notifications)" kf5-kpackage-devel kf6-kcolorscheme-devel kf6-kguiaddons-devel kf6-ki18n-devel kf6-kiconthemes-devel kf6-kirigami-devel kf6-frameworkintegration-devel kf6-kcmutils-devel kf5-kcmutils-devel kf5-frameworkintegration-devel
```

**Comment by tduck973564** [comment]
Seems to have fixed itself, after pulling and rebuilding. My bad
