### ISSUE TITLE
Minor alignment issue in tabbar

### ISSUE THREAD

**Issue by ams-sth** [Bali10050/Lightly#25]
![BugOne](https://github.com/user-attachments/assets/5ca9c874-9771-42c3-aafa-af75c217e012)

**Comment by Bali10050** [comment]
It's caused by e62f91a, I'll try fixing it as soon as possible

**Comment by ams-sth** [comment]
@Bali10050 After reverting the line to old value, The alignment has been fixed. Thank you!
