### ISSUE TITLE
Restore the signature toolbar buttons

### ISSUE THREAD

**Issue by hrqmonteiro** [Bali10050/Lightly#26]
Why did you move to a windows-like button instead of the original ones?

![image](https://github.com/user-attachments/assets/56991bc4-b724-4edf-888b-08fdd94929ab)
![image](https://github.com/user-attachments/assets/0f9f03f6-8f49-4182-924d-595cea4b8c9c)

Now this is the only fork working on Plasma 6 and you made it look exactly like Windows? Can i ask you why?

Couldn't be possible to add an option to have the default looking buttons or something?

This Windows-ish version is not good.

**Comment by Bali10050** [comment]
It hasn't been implemented yet, I'm using [klassy](https://github.com/paulmcauley/klassy) for it at the moment. I'm only working on the application theme at the moment, and if I change something that not all people might like, I add a way to easily opt-out. Like this: 

https://github.com/user-attachments/assets/ed8d5e18-ef46-40a0-a54f-23eb723324c9
