### ISSUE TITLE
Issue with Libreoffice 

### ISSUE THREAD

**Issue by ams-sth** [Bali10050/Lightly#30]
I don't know how to describe it accurately. It does seem like its related to spacing. 
![image](https://github.com/user-attachments/assets/f00984e6-1b5e-41ce-a214-db4862973c40)

**Comment by Bali10050** [comment]
It seems to be a problem when you have a global scale above 150%, I'll try my best to fix it, but at the moment I'm not sure that I have the skills to do that. I'll let you know if I find anything

**Comment by ams-sth** [comment]
Actually I am encountering this issue on 125% global scale at 1920 x 1080 screen resolution.

**Comment by ams-sth** [comment]
This issue persist on luwx/boehs version as well.

**Comment by Bali10050** [comment]
It seems to only happen when the menus are overflowing, if I remember correctly, this was the default behavior for breeze too, a couple of years ago

**Comment by ams-sth** [comment]
I  asked for solution to vinyl theme creator ekaaty as well and his response was:

" Libreoffice uses GTK themes, so the problem can be related to the one selected on the systemsettings, not to Vinyl application style. Please ensure you're using "Default" or "Breeze Dark" until Vinyl had implemented a GTK theme. Additionally, you can try to set the environment variable "QT_QPA_PLATFORM=xcb" temporally to see if problem is related to wayland. In that case, Fedora is about to fix a bug on it on upcomming packages of qt6-qtwayland. "

I tried both if it and it didn't work. I think the issue inclined more with LibreOffice than with Lightly and its fork.

**Comment by christiantosta** [comment]
Thanks for feedback. I can't understand why Fedora doesn't upgrade LO to 24.8.x.
