### ISSUE TITLE
Transparency/blur issue with context menu

### ISSUE THREAD

**Issue by subhasutra** [Bali10050/Lightly#32]
Opening up a few applications and right clicking on them is causing some visual issue. So far I've checked with dolphin and konsole. This is how the context menu looks while hovering over it.
![image](https://github.com/user-attachments/assets/f9c5618a-0f19-4cb8-ba86-0eb80e100ca4)

The hovered options have a different effect. This however only happens on first time right clicking, afterwards this doesn't occur and it behaves normally.

**Comment by christiantosta** [comment]
Wayland?

**Comment by Bali10050** [comment]
Can you tell me what color theme you're using? It would make it a bit easier to try to find the problem

**Comment by subhasutra** [comment]
I am using a custom colour scheme, however the issue persists with breeze light and dark as well. And yes I'm using wayland.

**Comment by christiantosta** [comment]
Menus 70% opaque is so low for me (I use 90%), but it's not the cause of problem. Works fine here with this amount.

Enablind the Kwin effects "Blur" and "Background Contrast" resolves the issue for you? Kwin effect "Transparency" appears to have some conflicts with Lightly.

**Comment by mashrit** [comment]
this is not just a lightly issue, this also happens with blurry kvantum themes like [layan](https://store.kde.org/p/1325246)

**Comment by christiantosta** [comment]
> this is not just a lightly issue, this also happens with blurry kvantum themes like [layan](https://store.kde.org/p/1325246)

Works for me with Vinyl and Lightly. But with Lightly,  the top rounded borders shows me a dark blue corner.

![image](https://github.com/user-attachments/assets/8f31ce64-7295-46c6-97ca-0529599a4a2f)

**Comment by Bali10050** [comment]
I can only see the wierd corner thing, but it's not blue for me, just blurred. But it seems that transparency needs a lot of work.

**Comment by subhasutra** [comment]
It's definitely a transparency issue, happens even without blur. Images for comparison.

First time right clicking to open context menu:
![image1](https://github.com/user-attachments/assets/160c0815-df8a-4c97-b274-18d51c571c63)

Next time onwards:
![image2](https://github.com/user-attachments/assets/86ae9724-fa52-412d-a943-c3cc0f5ea401)



> this is not just a lightly issue, this also happens with blurry kvantum themes like [layan](https://store.kde.org/p/1325246)

Can confirm, seeing it with kvantum as well.

**Comment by christiantosta** [comment]
Perhaps related with mesa or video drivers?

**Comment by Bali10050** [comment]
It could be, I'm running on amd, and I have no idea how to replicate this bug. Does this bug get away with a reboot or is it there every time you right click first after opening something?

**Comment by DeltaCopy** [comment]
https://github.com/tsujan/Kvantum/issues/967#issuecomment-2029578812

May want to check for this "[AdaptiveTransparency]" settings in the theme being used and disable it.

**Comment by subhasutra** [comment]
I think there is a mention of the problem in kvantum's [latest release](https://github.com/tsujan/Kvantum/releases/tag/V1.1.3), as the version 1.1.3 fixes the same problem. The release note says

> Qt 6.8.0 has a regression that randomly creates artifacts in translucent windows under Wayland. A workaround has been added for it, such that the windows/menus/tooltips which are made translucent by Kvantum are not affected by it.





> Perhaps related with mesa or video drivers?

I don't think mesa should be the issue, as downgrading didn't help.



> It could be, I'm running on amd, and I have no idea how to replicate this bug. Does this bug get away with a reboot or is it there every time you right click first after opening something?

It is persistent, happens every time I open a new window.



> [tsujan/Kvantum#967 (comment)](https://github.com/tsujan/Kvantum/issues/967#issuecomment-2029578812)
> 
> May want to check for this "[AdaptiveTransparency]" settings in the theme being used and disable it.

This didn't help.
