### ISSUE TITLE
Any way to update?

### ISSUE THREAD

**Issue by mashrit** [Bali10050/Lightly#37]
Is there any way to update the theme rather than installing it all again?

**Comment by Bali10050** [comment]
If you use the Fedora copr, you should be able to update it like any other package. If you install from the AUR, you can use [`yay`](https://github.com/Jguer/yay) or [`paru`](https://github.com/Morganamilo/paru) to update it with the other packages

**Comment by mashrit** [comment]
So, i have to use the aur got it
