### ISSUE TITLE
Split tab in dolpin by sliding out a tab to right side

### ISSUE THREAD

**Issue by Hellorge** [Bali10050/Lightly#41]
When we have tab bar length less than window width we can init a split view by dragging a tab from tab bar to right side outside of tab bar length.

**Comment by Bali10050** [comment]
Is this a feature request?

**Comment by Hellorge** [comment]
Yes, apologies if this isn't the correct place of place one.

**Comment by Bali10050** [comment]
I don't think that this is a feature that could be added by me, I think that dolphin devs could help you better with that, I don't think there's a way to do that without a lot of hacking. This project is like a css but a lot harder, we mostly work on the visual stuff.

**Comment by Hellorge** [comment]
Got it, thank you.
