### ISSUE TITLE
Menubar remains opaque with translucent toolbar and headerbar

### ISSUE THREAD

**Issue by subhasutra** [Bali10050/Lightly#43]
For translucent headerbar and toolbar I've added transparency to my colour scheme, which works as intended, but the menubar does not change.

![image](https://github.com/user-attachments/assets/05e9ee7b-9980-4230-ae88-c1f9e292d844)

I am not entirely sure, but this might be a recent regression. 

On a side note, the toolbar in kate remains opaque always (the only kde app I've encountered to do so, even kwrite uses the transparency). Do you think it might be possible to address that, even with an option in the settings perhaps.

**Comment by DeltaCopy** [comment]
I can repro this. Using the Glassly-Darker color scheme.

However, this issue was originally reported over on https://github.com/boehs/Lightly/issues/24
So I doubt this is a regression caused by any changes made to the code in this fork.

**Comment by mashrit** [comment]
![image](https://github.com/user-attachments/assets/98d246ee-a74a-4b96-8a9d-e9e5f982e490)
 
this is translucent for me

**Comment by DeltaCopy** [comment]
The issue is that the header and toolbar are both transparent but the menubar isn't.
It leaves a mismatch in the appearance of the app.
I think it is achievable to do but ultimately will require some further investigation in the code.

**Comment by mashrit** [comment]
ok, i get it, 
i know why the menubar is different

the menubar takes its colour from this value
![image](https://github.com/user-attachments/assets/42a597ea-c065-4d48-8557-7523a225b98a)

while the header and toolbar take from these values
![image](https://github.com/user-attachments/assets/4afc3957-4608-4360-bb57-736d1dbe4b42)

so, if you want a consistent theme both values should have the same opacity value

**Comment by subhasutra** [comment]
I don't think having to change window opacity for menubar is a good idea, as it causes unwanted parts of apps to be discoloured.
![image1](https://github.com/user-attachments/assets/452152ea-b279-47be-977a-efa02901632b)

In my opinion, menubar should inherit the values from either the headerbar or the toolbar, for example that is how it is done in Klassy.

**Comment by Bali10050** [comment]
> menubar should inherit the values from either the headerbar or the toolbar

I think this issue could be solved by a new option in the settings. I'll try making something like that in the weekend.

**Comment by subhasutra** [comment]
That looks promising, thank you for your efforts.

**Comment by subhasutra** [comment]
Thank you, it is now fixed, including kate as well.
