### ISSUE TITLE
Theme doesn't apply to QT5 apps

### ISSUE THREAD

**Issue by colin-intj** [Bali10050/Lightly#45]
Hello! Thank you for bringing back Lightly, it's quite possibly my favorite KDE theme and I'm glad I can finally use it in Plasma 6! I've noticed that, even when I set Lightly as my application style, QT5 apps still use Breeze.

![Screenshot_20241114_135939](https://github.com/user-attachments/assets/80a37106-2f63-4c8b-80d0-f5b64ee1d3c9)
_QT6 app (Dolphin) and QT5 app (qView) side-by-side_

Would it be possible for you to make the theme work for Qt5 apps as well? Thanks!

**Comment by Bali10050** [comment]
I'm 99% sure that you have a problem with your xdg-desktop-portal. Try installing `xdg-desktop-portal` and `xdg-desktop-portal-kde`. 
![](https://github.com/user-attachments/assets/3518c22b-55f5-496f-a187-de6a6011549a)

<https://wiki.archlinux.org/title/XDG_Desktop_Portal>

**Comment by subhasutra** [comment]
For me VLC still uses breeze. And the desktop portals are working fine for other apps.

**Comment by meisaamayako** [comment]
Can confirm this one. VLC and other QT5 apps do not use Lightly at all. both `xdg-desktop-portal` and `xdg-desktop-portal-kde` are installed as well.

```
Operating System: Arch Linux 
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.11.8-zen1-2-zen (64-bit)
Graphics Platform: Wayland
Processors: 4 × 11th Gen Intel® Core™ i3-1115G4 @ 3.00GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: LENOVO
Product Name: 81X8
System Version: IdeaPad 3 15ITL05
```

![17Sun081906](https://github.com/user-attachments/assets/8625db6a-35ba-4b8d-b8d5-530955a94754)

**Comment by Bali10050** [comment]
I'm not sure what the best solution would be, I don't think that bringing back qt5 for vlc is a good idea, while vlc has a new ui in development:
![Screenshot_20241117_180851](https://github.com/user-attachments/assets/6e9b7c18-a2db-4098-80fb-8aa185a9151e)

**Comment by DeltaCopy** [comment]
To get this to work the CMakeLists will need updating to include the QT5/KF5 build dependencies.
@Bali10050 let me know your thoughts as we've already removed those dependencies before.
Supporting both QT5 and QT6 builds is achievable but is it the correct path going forward, especially as Plasma has moved to QT6.

![vlc](https://github.com/user-attachments/assets/21a0672d-00a6-484b-9052-3e30e2243874)



@colin-intj  qview has already been ported over to QT6 so the Lightly style will work natively.
Which distro are you using ?

**Comment by colin-intj** [comment]
Sorry for the late reply. I'm currently running Fedora 41.

**Comment by colin-intj** [comment]
Sorry for the late reply, @Bali10050. Like @meisaamayako, I have it installed too.

**Comment by Bali10050** [comment]
@DeltaCopy if you have something working, we can add it as an option, but if not, I don't think it's a good idea to start working backwards.
