### ISSUE TITLE
nixos support

### ISSUE THREAD

**Issue by zspher** [Bali10050/Lightly#50]
Hi,

I've made a flake for this style for nixos, (https://github.com/zspher/Lightly/tree/feature-nix-flake)

**Comment by zspher** [comment]
should i make a PR for this or try to get a package in nixpkgs (maybe after the project is renamed)?

**Comment by Bali10050** [comment]
You can make a pr, I'll appreciate it. You can get the package in nixpkgs if it's not a problem for you, the renaming stuff isn't my main focus, I just want to maintain this project as long as there isn't something better, and improve it as much as I can.

**Comment by zspher** [comment]
closed by https://github.com/Bali10050/Lightly/pull/51
