### ISSUE TITLE
"Korners" bug is back on menus when using transparency

### ISSUE THREAD

**Issue by crimsonyote** [Bali10050/Lightly#53]
The infamous "Korners" bug has returned on Plasma 6.x when using transparency with Wayland, I am yet to test it on X11. However, the corners of menus are not rounded properly like on Plasma 5.x, causing them to retain sharp, blurred corners which would usually be hidden. I'm not sure what's causing this, but I have a suspicion it's related to scaling, as I use 125% on my laptop.

Here's my system info, in case it helps:
OS: Kubuntu 24.10
Plasma version: 6.1.5
QT version: 6.6.2
Kernel version: 6.11.0-9 Generic 
Wayland windowing system (Have not **yet** tested X11)

HW info:
HP ProBook 430 G8
Intel Core i5-1135G7 (4C 8T)
Intel Iris Xe graphics (80EUs)
16GB RAM (2x 8GB)
1TB SSD
1920x1080 display (125% scaling)

![Screenshot_20241204_134756](https://github.com/user-attachments/assets/e7064138-3613-4ba1-90da-21e93c542086)

**Comment by DeltaCopy** [comment]
The only thing I can think of is lowering the corner radius in the settings.

Also, to rule out this being a blur issue can you try disabling it and retrying.
Do you get the same result ?

**Comment by Bali10050** [comment]
`lightlyblurhelper.cpp` has this „roundedness” code, I haven't really read trough it yet, but the other parts of the code seem to use `StyleConfigData::cornerRadius()`
```cpp
QRegion roundedRegion(const QRect &rect, int radius, bool topLeft, bool topRight, bool bottomLeft, bool bottomRight)
    {
        QRegion region(rect, QRegion::Rectangle);

        if (topLeft) {
            // Round top-left corner.
            const QRegion topLeftCorner(rect.x(), rect.y(), radius, radius, QRegion::Rectangle);
            const QRegion topLeftRounded(rect.x(), rect.y(), 2 * radius, 2 * radius, QRegion::Ellipse);
            const QRegion topLeftEar = topLeftCorner - topLeftRounded;
            region -= topLeftEar;
        }
        
        if (topRight) {
            // Round top-right corner.
            const QRegion topRightCorner(
                rect.x() + rect.width() - radius, rect.y(),
                radius, radius, QRegion::Rectangle);
            const QRegion topRightRounded(
                rect.x() + rect.width() - 2 * radius, rect.y(),
                2 * radius, 2 * radius, QRegion::Ellipse);
            const QRegion topRightEar = topRightCorner - topRightRounded;
            region -= topRightEar;
        }

        if (bottomRight) {
            // Round bottom-right corner.
            const QRegion bottomRightCorner(
                rect.x() + rect.width() - radius, rect.y() + rect.height() - radius,
                radius, radius, QRegion::Rectangle);
            const QRegion bottomRightRounded(
                rect.x() + rect.width() - 2 * radius, rect.y() + rect.height() - 2 * radius,
                2 * radius, 2 * radius, QRegion::Ellipse);
            const QRegion bottomRightEar = bottomRightCorner - bottomRightRounded;
            region -= bottomRightEar;
        }
        
        if (bottomLeft){
            // Round bottom-left corner.
            const QRegion bottomLeftCorner(
                rect.x(), rect.y() + rect.height() - radius,
                radius, radius, QRegion::Rectangle);
            const QRegion bottomLeftRounded(
                rect.x(), rect.y() + rect.height() - 2 * radius,
                2 * radius, 2 * radius, QRegion::Ellipse);
            const QRegion bottomLeftEar = bottomLeftCorner - bottomLeftRounded;
            region -= bottomLeftEar;
        }

        return region;
    }
```
#32 is probably related

**Comment by mashrit** [comment]
can confirm happens on x11

**Comment by DeltaCopy** [comment]
Made some code changes.

This is how it looks now with fractional scaling set to 125%
Menu transparency is at 100%

![image](https://github.com/user-attachments/assets/6765822a-f69a-447d-9cab-ae201ebdbd5c)

There is still some slight clipping.
So minor adjustments still required in how the frame is being rendered.

**Comment by DeltaCopy** [comment]
The downside to the changes made is that the corner radius settings are lowered to 5 being the max rather than 8.
Breeze has a hardcoded radius set to 5 which appears to be on purpose to avoid all these problems with how the menu frames are rendered.

**Comment by Bali10050** [comment]
2751ab3 should mostly fix the issue, it blurs correctly even with an absurdly high blur radius.
![Screenshot_20241208_161125](https://github.com/user-attachments/assets/e7f3398c-6bbc-483e-bd54-1e1921aeb6e9)

**Comment by crimsonyote** [comment]
I just updated to the latest version today. Anyone know why the outlines look weird now with transparency? In this example screenshot I set it to 20% transparency, but with higher values this glitch is less noticable. All of the settings I mentioned in the original post are the same, apart from the transparency.

![wat](https://github.com/user-attachments/assets/8f864bb6-633c-416d-a814-ea45b847e737)

**Comment by Bali10050** [comment]
![Screenshot_20241224_125002](https://github.com/user-attachments/assets/57c3ad26-e7ba-44ad-bfae-14400d88b3a2)

It looks mostly normal for me, are you on Kubuntu 24.10 too?

**Comment by crimsonyote** [comment]
Apologies for the late reply. Yes, I'm on Kubuntu. I can see the same effect in your image you shared here - note that the border **around** the menu's edges are 100% transparent. Usually these would be slightly darker than the menu itself.

**Comment by Bali10050** [comment]
#84 should fix that issue, I'll merge the fix and all the other stuff once I get home on the 1st of january, until then, you can use the [FeatureDarkly](https://github.com/Bali10050/Darkly/tree/FeatureDarkly) branch
