### ISSUE TITLE
AUR Bin Package 

### ISSUE THREAD

**Issue by sintaulsiam** [Bali10050/Lightly#57]
Sorry , I am asking for more work. But please make a -bin version of AUR package. Its hard to compile it on older devices , some times I fail to clone this large repo, is it necessary to clone the entire। So a bin version of the package would help plz consider it. those chaotic-aur people wont hear.

**Comment by Bali10050** [comment]
There's a binary for archlinux in the [releases](https://github.com/Bali10050/Lightly/releases) tab.
After downloading, you can install it using this command:
```
sudo pacman -U ~/Downloads/lightly-*.*.*-x86_64.pkg.zst
```

**Comment by sintaulsiam** [comment]
Yeah, I have already done it. However, having it in AUR will help when updating using AUR helper.

**Comment by sintaulsiam** [comment]
I

**Comment by DeltaCopy** [comment]
@sintaulsiam

https://aur.archlinux.org/packages/lightly-qt6-bin

**Comment by sintaulsiam** [comment]
Thank you, thank you so much.
