### ISSUE TITLE
Show version somewhere in Lightly settings.

### ISSUE THREAD

**Issue by huestack** [Bali10050/Lightly#62]
Please add a new tab About, or add version at bottom of settings window.

**Comment by Bali10050** [comment]
Now it should name itself based on the name of the build folder, when installed with `install.sh`.  The other build methods need a bit of adjustment, until then, some of them will just display `LIGHTLY_VERSION` in the corner
![Screenshot_20241213_014048](https://github.com/user-attachments/assets/9bf10f7d-a20b-4b11-bfe7-abf0148bfbe1)

**Comment by huestack** [comment]
Thank you for this and thank you for picking up this project.

**Comment by Bali10050** [comment]
The project now uses DeltaCopy's way of versioning, from v0.5.11 it should display correctly everywhere
![Installed using lightly-0.5.11-x86_64.pkg.zst](https://github.com/user-attachments/assets/0ed83065-45bc-44db-94a3-434da1ec253c)
