### ISSUE TITLE
Adding scrolling to longer menu lists

### ISSUE THREAD

**Issue by subhasutra** [Bali10050/Lightly#69]
Would it be possible to add a scrolling option to limit the long menu lists. Currently it spans as much area as it needs to show everything. 
<details>
<summary>Breeze</summary>
<img src="https://github.com/user-attachments/assets/38b3b951-c1a8-45ec-b514-d51660315fe8" alt="breeze-menu.png">
</details>
<details>
<summary>Lightly</summary>
<img src="https://github.com/user-attachments/assets/2d268ec0-13ea-45e6-b049-e52a38d732ae" alt="lightly-menu.png">
</details>

**Comment by DeltaCopy** [comment]
#72 may fix this.

![scedit](https://github.com/user-attachments/assets/e42e5825-f4af-469c-8575-055bf074ffc6)

**Comment by subhasutra** [comment]
Yes it fixes the issue, thank you very much!

**Comment by ams-sth** [comment]
I am encountering this issue in Kdevelop, the scroll to top might have a small bug. I am using fedora 41.
![image](https://github.com/user-attachments/assets/d208e214-be02-42fe-8a8b-abcd993f3272)
![image](https://github.com/user-attachments/assets/508c17f9-759d-471a-b8ee-dfe1bd833162)
